// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKSOfraZyWuj3Fne_XMpSHTkvij6CqH_4',
    appId: '1:123732427850:web:8378583dc27a2a25c512b3',
    messagingSenderId: '123732427850',
    projectId: 'todoappdb-44283',
    authDomain: 'todoappdb-44283.firebaseapp.com',
    storageBucket: 'todoappdb-44283.appspot.com',
    measurementId: 'G-CZ4BBD6RMF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLVOE6lftm5PdRKYI63oynqPIoygRYlOc',
    appId: '1:123732427850:android:557e869e678d4f07c512b3',
    messagingSenderId: '123732427850',
    projectId: 'todoappdb-44283',
    storageBucket: 'todoappdb-44283.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8EV3P1x0C6eSpXbmpMglXRHslklxzVfE',
    appId: '1:123732427850:ios:32005be88dd58fcac512b3',
    messagingSenderId: '123732427850',
    projectId: 'todoappdb-44283',
    storageBucket: 'todoappdb-44283.appspot.com',
    iosBundleId: 'com.skillrisers.todoappBrainmentors',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8EV3P1x0C6eSpXbmpMglXRHslklxzVfE',
    appId: '1:123732427850:ios:32005be88dd58fcac512b3',
    messagingSenderId: '123732427850',
    projectId: 'todoappdb-44283',
    storageBucket: 'todoappdb-44283.appspot.com',
    iosBundleId: 'com.skillrisers.todoappBrainmentors',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKSOfraZyWuj3Fne_XMpSHTkvij6CqH_4',
    appId: '1:123732427850:web:392f6bd40dace157c512b3',
    messagingSenderId: '123732427850',
    projectId: 'todoappdb-44283',
    authDomain: 'todoappdb-44283.firebaseapp.com',
    storageBucket: 'todoappdb-44283.appspot.com',
    measurementId: 'G-98CMQLDBWG',
  );
}
